name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore XamarinUnitTesting.UnitTests/XamarinUnitTesting.UnitTests.csproj
    - name: Build
      run: dotnet build XamarinUnitTesting.UnitTests/XamarinUnitTesting.UnitTests.csproj --no-restore
    - name: Test
      run: dotnet test XamarinUnitTesting.UnitTests/XamarinUnitTesting.UnitTests.csproj --no-build --verbosity normal
